// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAVEvYICn5mBMACC6zbq45IGNUDe3hR_o',
    appId: '1:394710791043:web:c6ceddf54b5adb836cbcb6',
    messagingSenderId: '394710791043',
    projectId: 'notecraft-375a7',
    authDomain: 'notecraft-375a7.firebaseapp.com',
    storageBucket: 'notecraft-375a7.appspot.com',
    measurementId: 'G-R19F4F6GC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVTLhvjQW6zcp1ftGy-VthCZlC2IkVQWg',
    appId: '1:394710791043:android:d1ad6eda52e0994e6cbcb6',
    messagingSenderId: '394710791043',
    projectId: 'notecraft-375a7',
    storageBucket: 'notecraft-375a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBth497eAO_wTXbb8vKyGG4A4oBY1atO3o',
    appId: '1:394710791043:ios:dc018f98ef38a6a36cbcb6',
    messagingSenderId: '394710791043',
    projectId: 'notecraft-375a7',
    storageBucket: 'notecraft-375a7.appspot.com',
    iosBundleId: 'com.example.notecraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBth497eAO_wTXbb8vKyGG4A4oBY1atO3o',
    appId: '1:394710791043:ios:65467a80e5d125ec6cbcb6',
    messagingSenderId: '394710791043',
    projectId: 'notecraft-375a7',
    storageBucket: 'notecraft-375a7.appspot.com',
    iosBundleId: 'com.example.notecraft.RunnerTests',
  );
}
